apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: sre-frontend
  endpoints:
  - port: http
    path: /metrics
