apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username TEXT NOT NULL,
        password TEXT NOT NULL
    );

    INSERT INTO users (username, password) VALUES (
        'admin',
        'pbkdf2:sha256:260000$wDrhxP4QQNjRRYdh$387c3da23c4046c9bf33738f5123f0c27b6c5ba610fb651ba06dd993bac6814c'
    ) ON CONFLICT DO NOTHING;
